
#ifndef PROMAKE_DEBUG_H_INCLUDED
#define PROMAKE_DEBUG_H_INCLUDED


#ifdef PROMAKE_DEBUG_OUTPUT
  #define PROMAKE_LIB_DEBUG_OUTPUT      PROMAKE_DEBUG_OUTPUT
  #warning Use Serial for debug
#else
  #define PROMAKE_LIB_DEBUG_OUTPUT      Serial
#endif

// Change _PROMAKE_LOGLEVEL_ to set tracing and logging verbosity
// 0: DISABLED: no logging
// 1: ERROR: errors
// 2: WARN: errors and warnings
// 3: INFO: errors, warnings and informational (default)
// 4: DEBUG: errors, warnings, informational and debug

#ifndef _PROMAKE_LOGLEVEL_
  #define _PROMAKE_LOGLEVEL_       1
#endif

#define PROMAKE_DEBUG_PRINT        PROMAKE_LIB_DEBUG_OUTPUT.print
#define PROMAKE_DEBUG_PRINTLN      PROMAKE_LIB_DEBUG_OUTPUT.println

const char PROMAKE_MARK[] = "[PRMK] ";
const char PROMAKE_SP[]   = " ";

#define PROMAKE_DEBUG_PRINT_MARK   PROMAKE_DEBUG_PRINT(PROMAKE_MARK)
#define PROMAKE_DEBUG_PRINT_SP     PROMAKE_DEBUG_PRINT(PROMAKE_SP)

#if _PROMAKE_LOGLEVEL_ > 3

#define PROMAKE_LOGERROR(x)    PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINTLN(x);
#define PROMAKE_LOGERROR1(x,y) PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINT(x); PROMAKE_DEBUG_PRINT_SP; PROMAKE_DEBUG_PRINTLN(y);
#define PROMAKE_LOGWARN(x)     PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINTLN(x);
#define PROMAKE_LOGWARN1(x,y)  PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINT(x); PROMAKE_DEBUG_PRINT_SP; PROMAKE_DEBUG_PRINTLN(y);
#define PROMAKE_LOGINFO(x)     PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINTLN(x);
#define PROMAKE_LOGINFO1(x,y)  PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINT(x); PROMAKE_DEBUG_PRINT_SP; PROMAKE_DEBUG_PRINTLN(y);
//////////////////////////////////////////////
#define PROMAKE_LOGDEBUG(x)      PROMAKE_DEBUG_PRINTLN(x);
#define PROMAKE_LOGDEBUG0(x)     PROMAKE_DEBUG_PRINT(x);
#define PROMAKE_LOGDEBUG1(x,y)   PROMAKE_DEBUG_PRINT(x); PROMAKE_DEBUG_PRINT_SP; PROMAKE_DEBUG_PRINTLN(y);
#define PROMAKE_LOGDEBUG2(x,y,z) PROMAKE_DEBUG_PRINT(x); PROMAKE_DEBUG_PRINT_SP; PROMAKE_DEBUG_PRINT(y); PROMAKE_DEBUG_PRINT_SP; PROMAKE_DEBUG_PRINTLN(z);
#define PROMAKE_LOGDEBUG3(...)   PROMAKE_DEBUG_PRINT("[");PROMAKE_DEBUG_PRINT(__FUNCTION__); PROMAKE_DEBUG_PRINT("(): "); PROMAKE_DEBUG_PRINT(__LINE__); PROMAKE_DEBUG_PRINT(" ] "); PROMAKE_DEBUG_PRINTLN(__VA_ARGS__);

#elif  _PROMAKE_LOGLEVEL_ > 2

#define PROMAKE_LOGERROR(x)    PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINTLN(x);
#define PROMAKE_LOGERROR1(x,y) PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINT(x); PROMAKE_DEBUG_PRINT_SP; PROMAKE_DEBUG_PRINTLN(y);
#define PROMAKE_LOGWARN(x)     PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINTLN(x);
#define PROMAKE_LOGWARN1(x,y)  PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINT(x); PROMAKE_DEBUG_PRINT_SP; PROMAKE_DEBUG_PRINTLN(y);
#define PROMAKE_LOGINFO(x)     PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINTLN(x);
#define PROMAKE_LOGINFO1(x,y)  PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINT(x); PROMAKE_DEBUG_PRINT_SP; PROMAKE_DEBUG_PRINTLN(y);
//////////////////////////////////////////////
#define PROMAKE_LOGDEBUG(x)      ;
#define PROMAKE_LOGDEBUG0(x)     ;
#define PROMAKE_LOGDEBUG1(x,y)   ;
#define PROMAKE_LOGDEBUG2(x,y,z) ;
#define PROMAKE_LOGDEBUG3(...)   ;

#elif  _PROMAKE_LOGLEVEL_ > 1

#define PROMAKE_LOGERROR(x)    PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINTLN(x);
#define PROMAKE_LOGERROR1(x,y) PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINT(x); PROMAKE_DEBUG_PRINT_SP; PROMAKE_DEBUG_PRINTLN(y);
#define PROMAKE_LOGWARN(x)     PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINTLN(x);
#define PROMAKE_LOGWARN1(x,y)  PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINT(x); PROMAKE_DEBUG_PRINT_SP; PROMAKE_DEBUG_PRINTLN(y);
#define PROMAKE_LOGINFO(x)     ;
#define PROMAKE_LOGINFO1(x,y)  ;
//////////////////////////////////////////////
#define PROMAKE_LOGDEBUG(x)      ;
#define PROMAKE_LOGDEBUG0(x)     ;
#define PROMAKE_LOGDEBUG1(x,y)   ;
#define PROMAKE_LOGDEBUG2(x,y,z) ;
#define PROMAKE_LOGDEBUG3(...)   ;

#elif  _PROMAKE_LOGLEVEL_ > 0

#define PROMAKE_LOGERROR(x)    PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINTLN(x);
#define PROMAKE_LOGERROR1(x,y) PROMAKE_DEBUG_PRINT_MARK; PROMAKE_DEBUG_PRINT(x); PROMAKE_DEBUG_PRINT_SP; PROMAKE_DEBUG_PRINTLN(y);
#define PROMAKE_LOGWARN(x)     ;
#define PROMAKE_LOGWARN1(x,y)  ;
#define PROMAKE_LOGINFO(x)     ;
#define PROMAKE_LOGINFO1(x,y)  ;
//////////////////////////////////////////////
#define PROMAKE_LOGDEBUG(x)      ;
#define PROMAKE_LOGDEBUG0(x)     ;
#define PROMAKE_LOGDEBUG1(x,y)   ;
#define PROMAKE_LOGDEBUG2(x,y,z) ;
#define PROMAKE_LOGDEBUG3(...)   ;

#else

#define PROMAKE_LOGERROR(x)    ;
#define PROMAKE_LOGERROR1(x,y) ;
#define PROMAKE_LOGWARN(x)     ;
#define PROMAKE_LOGWARN1(x,y)  ;
#define PROMAKE_LOGINFO(x)     ;
#define PROMAKE_LOGINFO1(x,y)  ;
//////////////////////////////////////////////
#define PROMAKE_LOGDEBUG(x)      ;
#define PROMAKE_LOGDEBUG0(x)     ;
#define PROMAKE_LOGDEBUG1(x,y)   ;
#define PROMAKE_LOGDEBUG2(x,y,z) ;
#define PROMAKE_LOGDEBUG3(...)   ;
#endif


#endif
